spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: jwt-spring-boot
  profiles:
    active: ${PROFILE:dev}
  threads:
    virtual:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: create
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}
  # Configuración de correo electrónico
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # Configuración de subida de archivos
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Configuración de archivos
file:
  upload-dir: ${UPLOAD_DIRECTORY:uploads}

server:
  port: ${PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}
  servlet:
    context-path: /api

app:
  url:
    frontend: ${FRONTEND_URL:http://localhost:3000}
  jwt:
    expirationMs: ${JWT_EXPIRATION_MS}
    jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS}
    issuer: programandoenjava.com
  # Configuración de emails
  email:
    from: ${EMAIL_FROM}
    activation-url: ${ACTIVATION_URL}
    reset-password-url: ${RESET_PASSWORD_URL}
  # Configuración de almacenamiento
  storage:
    upload-dir: ${UPLOAD_DIRECTORY:uploads}
    base-url: ${STORAGE_BASE_URL:http://localhost:8080/api/uploads}

sgd:
  api:
    url: ${SGD_API_URL:http://localhost:8082/api}
    token: ${SGD_API_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbi1hcGkiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE1MTYyMzkwMjJ9.8oF8OiGz8YV_xhyJ9NX7HJ8Js97paBkP8JWON8QxgE8}
